services:
  # Laravel Service
  laravel:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - ./back:/var/www  # Ensure this points to the correct Laravel directory
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  # MySQL Database Service
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin Service (Web Interface for MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql  # Links to the MySQL service
      PMA_PORT: 3306   # MySQL port
      PMA_ARBITRARY: 0
    ports:
      - "8080:80"     # Expose phpMyAdmin on port 8080
    depends_on:
      - mysql

  # React Service
  react:
    build:
      context: ./front  # Path to your React project
      dockerfile: Dockerfile
    container_name: react_app
    restart: always
    volumes:
      - ./front:/app  # Ensure this points to the correct React directory
      - /app/node_modules
    ports:
      - "3000:3000"

volumes:
  mysql_data: